version: 2

build:
    os: ubuntu-22.04
    tools:
      python: "3.12"
    jobs:
      pre_build:
        - sphinx-apidoc -o forte2/docs/source/ forte2/forte2/.

sphinx:
    configuration: forte2/docs/source/conf.py

python:
  install:
    - requirements: forte2/docs/requirements.txt
