version: 2

build:
    os: ubuntu-22.04
    tools:
      python: "mambaforge-22.9"
    jobs:
      pre_build:
        - sphinx-apidoc -o docs/source/ forte2/.

conda:
  environment: environment.yml

sphinx:
    configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - "--no-build-isolation"
        - "--verbose"
    - requirements: docs/requirements.txt
