version: 2

build:
    os: ubuntu-22.04
    tools:
      python: "3.12"
    jobs:
      pre_build:
        - sphinx-apidoc -o docs/source/ forte2/.

sphinx:
    configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
