version: 2

build:
    os: ubuntu-22.04
    tools:
      python: "miniconda-latest"
    jobs:
      pre_build:
        - sphinx-apidoc -o docs/source/ forte2/.

conda:
  environment: environment.yml

sphinx:
    configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
