"""Elementary-block contraction kernels for spin-free DSRG-MRPT3.

Generated by codegen/gen_kernels.py from the working equations in codegen/terms.py,
which hold them once in composite hole/particle/general indices. Every term is
expanded over the elementary core/active/virtual blocks and the combinations
that cannot contribute are dropped: an amplitude block outside its
hole-particle support, or an output block that is not off-diagonal.

Do not edit by hand. Change codegen/terms.py and regenerate.
"""

import numpy as np

# Blocking makes most contractions small, and for a small one numpy spends
# longer deriving a contraction path than performing the contraction. Choosing
# per call is worth about 10% end to end (N2/cc-pVTZ 4.6 -> 4.0 s; cc-pVDZ
# 1.66 -> 1.44 s) -- far less than a single-contraction microbenchmark suggests,
# since most of the work sits in the contractions large enough to take the
# optimized path either way.
#
# The test is the cost of contracting naively: the product over the union of the
# indices, not the operand sizes, which understate it by orders of magnitude.
# Because that is a count of operations rather than a size, the threshold does
# not need retuning per system. Measured optimum, flat to within a few percent
# between 20_000 and 200_000 and rising sharply above it (2e6 -> 5.2 s,
# 2e7 -> 12.4 s at cc-pVTZ).
#
# Three or more operands always go through the optimizer: an unoptimized
# multi-operand einsum contracts over every index at once, which is the trap
# `_df` sidesteps.
_NAIVE_MAX = 200_000


def einsum(spec, *ops, **kwargs):
    if len(ops) == 2:
        lhs = spec.split("->")[0]
        dims = {}
        for idx, o in zip(lhs.split(","), ops):
            for c, n in zip(idx, o.shape):
                dims[c] = n
        work = 1
        for n in dims.values():
            work *= n
        if work <= _NAIVE_MAX:
            return np.einsum(spec, *ops, optimize=False, **kwargs)
    return np.einsum(spec, *ops, optimize=True, **kwargs)


class _DSRGBlockHelper:
    """Spin-free DSRG-MRPT3 commutators, contracted block by block.

    Operators are dicts keyed by an elementary block label whose characters
    correspond one for one to the tensor's indices, so every contraction runs
    on a contiguous array and no composite index is ever sliced.

    A kernel whose operand is itself a commutator has an ``_od`` variant, pruned
    to the off-diagonal blocks such an operand can occupy -- the same split the
    two-component code makes with its ``_non_od`` kernels.
    """

    def __init__(self, dsrg_obj):
        self.ncore = dsrg_obj.ncore
        self.nact = dsrg_obj.nact
        self.nvirt = dsrg_obj.nvirt
        self.dims = {"c": self.ncore, "a": self.nact, "v": self.nvirt}

    def make_tensor(self, labels):
        return {b: np.zeros(tuple(self.dims[c] for c in b)) for b in labels}

    def make_1body(self):
        return self.make_tensor(ALL1_LABELS)

    def make_2body(self):
        return self.make_tensor(OD2_LABELS)

    # fmt: off
    def _df(self, out, blk, pblk, coef, spec, h2_pos, h2_blk, B, others):
        """Contract a term whose integral block has three or more virtual indices.

        Those blocks are never stored. Since V[pqrs] = sum_Q B[Q,p,r] B[Q,q,s],
        the two three-index factors enter the contraction in place of the block.

        The two pairwise steps are spelled out rather than handed to einsum as
        one three-operand contraction: left to choose, it picks an order that
        runs in its own kernel instead of reaching BLAS, which costs a factor of
        about seventy. The first step absorbs every index the second no longer
        needs; the auxiliary index is then walked in chunks sized from the
        intermediate that survives it.

        Sizing the chunk per contraction, from the intermediate it actually
        carries, is what makes this work. Capping the number of chunks instead
        was measured and is worse on both axes -- at cc-pVQZ a cap of sixteen
        gives 5.3 s and 148 MiB where sizing by memory alone gives 5.0 s and
        108 MiB -- because a uniform count is too coarse for some contractions
        and too fine for others.
        """
        ins, res = spec.split("->")
        ins = ins.split(",")
        w, x, y, z = ins[h2_pos]
        rest = ins[:h2_pos] + ins[h2_pos + 1:]
        b1, b2 = B[h2_blk[0] + h2_blk[2]], B[h2_blk[1] + h2_blk[3]]
        s1, s2 = "Q" + w + y, "Q" + x + z

        # an index survives the first step only if the second step still wants it
        keep = (set(s1) | set("".join(rest))) & (set(s2) | set(res))
        mid = "Q" + "".join(sorted(keep - {"Q"}))
        spec_a = ",".join([s1] + rest) + "->" + mid
        spec_b = mid + "," + s2 + "->" + res

        dim = {}
        for idx, arr in zip([s1, s2] + rest, [b1, b2] + list(others)):
            for c, n in zip(idx, arr.shape):
                dim[c] = n
        per = 1
        for c in mid[1:]:
            per *= dim[c]
        naux = b1.shape[0]
        chunk = max(1, min(naux, _DF_TARGET // max(per, 1)))

        perm = (1, 0) if len(res) == 2 else (1, 0, 3, 2)
        for q0 in range(0, naux, chunk):
            sl = slice(q0, q0 + chunk)
            val = einsum(spec_b, einsum(spec_a, b1[sl], *others), b2[sl])
            val *= coef
            out[blk] += val
            if pblk is not None:
                out[pblk] += val.transpose(perm)
